# Learn more about filters
# https://api-platform.com/docs/core/filters

# Filters have to be added into the entity through @ApiResource > attributes > filters
services:
  book.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments: [ { title: 'partial' } ]
    tags: [ 'api_platform.filter' ]
  # Add filter on Book relation to get all reviews related to a book
  # ie: http://127.0.0.1:8000/reviews?book=1
  review.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments: [ { book: 'exact' } ]
    tags: [ 'api_platform.filter' ]
  # ie: http://127.0.0.1:8000/reviews?publicationDate[before]=2016-09-11
  review.publication_date_filter:
    parent: 'api_platform.doctrine.orm.date_filter'
    arguments: [ { publicationDate: ~ } ]
    tags:  [ 'api_platform.filter' ]